version: '3.7'

services:

  master:
    image: mysql:8.0
    volumes:
      - ./docker/db/master/data:/var/lib/mysql
      - ./docker/db/master/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/db/master/sql:/docker-entrypoint-initdb.d
    tty: true
    environment:
      TZ: 'Asia/Tokyo'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_DATABASE: master_data
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  slave:
    image: mysql:8.0
    volumes:
      - ./docker/db/slave/data:/var/lib/mysql
      - ./docker/db/slave/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/db/slave/sql:/docker-entrypoint-initdb.d
    tty: true
    environment:
      TZ: 'Asia/Tokyo'
      MYSQL_ROOT_PASSWORD: 'password'
    command:  mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    depends_on:
      - master
